name: JavalinInBukkit
main: io.hanbings.javalin.bukkit.JavalinPlugin
version: 1.0.0
api_version: 1.13
libraries:
  - "io.javalin:javalin:4.4.0"
  - "org.slf4j:slf4j-simple:1.7.36"
  - "com.fasterxml.jackson.core:jackson-databind:2.13.2"